# Lookups
names_lookup = {
    'Deutzer BrÃ¼cke': 'Deutzer Brücke',
    'Deutzer Br�cke': 'Deutzer Brücke',
    'HohenzollernbrÃ¼cke': 'Hohenzollernbrücke',
    'Hohenzollernbr�cke': 'Hohenzollernbrücke',
    'Neumarkt': 'Neumarkt',
    'Z�lpicher Stra�e': 'Zülpicher Straße',
    'ZÃ¼lpicher StraÃŸe': 'Zülpicher Straße',
    'ZÃ¼lpicher StraÃe': 'Zülpicher Straße',
    'Bonner Stra�e': 'Bonner Straße',
    'Bonner StraÃŸe': 'Bonner Straße',
    'Bonner StraÃe': 'Bonner Straße',
    'Venloer Stra�e': 'Venloer Straße',
    'Venloer StraÃŸe': 'Venloer Straße',
    'Venloer StraÃe': 'Venloer Straße',
    'Vorgebirgswall': 'Vorgebirgswall',
    'Universit�ts-stra�e': 'Universitätsstraße',
    'UniversitÃ¤ts-straÃe': 'Universitätsstraße',
    'UniversitÃ¤ts-straÃŸe': 'Universitätsstraße',
    'Universitäts-straße': 'Universitätsstraße',
    'A.-Sch�tte-Allee': 'A.-Schütte-Allee',
    'A.-SchÃ¼tte-Allee': 'A.-Schütte-Allee',
    'Vorgebirgspark': 'Vorgebirgspark',
    'A.-Silbermann-Weg': 'A.-Silbermann-Weg',
    'Stadtwald': 'Stadtwald',
    'Niederl�nder Ufer': 'Niederländer Ufer',
    'NiederlÃ¤nder Ufer': 'Niederländer Ufer',
    'Rodenkirchener Br�cke': 'Rodenkirchener Brücke',
    'Rodenkirchener BrÃ¼cke': 'Rodenkirchener Brücke',
    'Severinsbr�cke': 'Severinsbrücke',
    'SeverinsbrÃ¼cke': 'Severinsbrücke',
    'Neusser Stra�e': 'Neusser Straße',
    'Neusser StraÃŸe': 'Neusser Straße'
}

months_lookup = {
    'Januar': "1",
    'Jan': "1",
    'Februar': "2",
    'Feb': "2",
    'März': "3",
    'M�rz': "3",
    'MÃ¤rz': "3",
    'Mar': "3",
    'Mrz': "3",
    'April': "4",
    'Apr': "4",
    'Mai': "5",
    'May': "5",
    'Juni': "6",
    'Jun': "6",
    'Juli': "7",
    'Jul': "7",
    'August': "8",
    'Aug': "8",
    'September': "9",
    'Sep': "9",
    'Oktober': "10",
    'Okt': "10",
    'November': "11",
    'Nov': "11",
    'Dezember': "12",
    'Dez': "12",
    'Dec': "12"
}